<?php

/**
 * @file
 * Contains isced_code.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isced_code_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isced_code module.
    case 'help.page.isced_code':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ISCED codes as select options') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_info_alter().
 *
 * @todo Remove once minimum version supported is at least 10.2.0.
 */
function isced_code_field_info_alter(array &$info): void {
  // Allow module to work with older versions of Drupal.
  if (\version_compare(\Drupal::VERSION, '10.1.9999', '<')) {
    $info['isced_code']['category'] = t("General");
  }
}
