<?php

/**
 * @file
 * Contains isced_code.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isced_code_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isced_code module.
    case 'help.page.isced_code':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ISCED codes as select options') . '</p>';
      return $output;

    default:
  }
}
